2022-01-13 21:54:50,743 INFO: Initialized curve data.
2022-01-13 21:54:50,747 INFO: Setting up initial twist data...
2022-01-13 21:54:52,038 INFO: Twist setup complete.
2022-01-13 21:54:52,038 INFO: Searching for rational points on each twist...
2022-01-13 21:54:54,754 INFO: Finished searching for rational points on each twist.
2022-01-13 21:54:54,755 INFO: Testing local solvability of twists...
2022-01-13 21:54:54,761 INFO: Finished local solvability testing.
2022-01-13 21:54:54,763 INFO: Computing elliptic curve a-invariants...
2022-01-13 21:55:13,192 INFO: Finished computation of a-invariants.
2022-01-13 21:55:13,194 INFO: Computing MW group (delta = ['-1', '-1'], g = [-4, 1, 10, -1, 2, 9])...
2022-01-13 21:56:22,455 INFO: Finished MW computation (delta = ['-1', '-1'], g = [-4, 1, 10, -1, 2, 9])
2022-01-13 21:56:22,459 INFO: Computing MW group (delta = ['4', '0', '-9', '1', '-2', '-9'], g = [-4, 1, 10, -1, 2, 9])...
2022-01-13 21:59:12,572 INFO: Finished MW computation (delta = ['4', '0', '-9', '1', '-2', '-9'], g = [-4, 1, 10, -1, 2, 9])
2022-01-13 21:59:12,575 INFO: Computing MW group (delta = ['1'], g = [-4, 1, 10, -1, 2, 9])...
2022-01-13 22:04:41,795 INFO: Finished MW computation (delta = ['1'], g = [-4, 1, 10, -1, 2, 9])
2022-01-13 22:04:41,798 INFO: Computing MW group (delta = ['-4', '0', '8', '-2', '2', '9'], g = [-4, 1, 10, -1, 2, 9])...
2022-01-14 00:23:10,011 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16359.8MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
