2022-01-12 09:25:54,614 INFO: Initialized curve data.
2022-01-12 09:25:54,617 INFO: Setting up initial twist data...
2022-01-12 09:25:55,677 INFO: Twist setup complete.
2022-01-12 09:25:55,677 INFO: Searching for rational points on each twist...
2022-01-12 09:25:58,606 INFO: Finished searching for rational points on each twist.
2022-01-12 09:25:58,607 INFO: Testing local solvability of twists...
2022-01-12 09:26:08,475 INFO: Finished local solvability testing.
2022-01-12 09:26:08,476 INFO: Computing elliptic curve a-invariants...
2022-01-12 09:26:14,480 INFO: Finished computation of a-invariants.
2022-01-12 09:26:14,483 INFO: Skipped MW computation because no base point (delta = ['1/2', '7/2', '11', '16', '9/2', '-15/2'])
2022-01-12 09:26:14,483 INFO: Computing MW group (delta = ['-1/2', '-1/2', '1'], g = [1, 1])...
2022-01-12 09:26:14,751 INFO: Finished MW computation (delta = ['-1/2', '-1/2', '1'], g = [1, 1])
2022-01-12 09:26:14,755 INFO: Computing MW group (delta = ['-1/2', '-1/2', '1'], g = [-4, -20, -32, -9, 15])...
2022-01-12 09:26:34,320 INFO: Finished MW computation (delta = ['-1/2', '-1/2', '1'], g = [-4, -20, -32, -9, 15])
2022-01-12 09:26:34,325 INFO: Computing MW group (delta = ['1'], g = [1, 1])...
2022-01-12 09:26:34,668 INFO: Finished MW computation (delta = ['1'], g = [1, 1])
2022-01-12 09:26:34,671 INFO: Computing MW group (delta = ['1'], g = [-4, -20, -32, -9, 15])...
2022-01-12 10:52:16,398 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16377.8MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
