2022-01-11 12:29:21,225 INFO: Initialized curve data.
2022-01-11 12:29:21,228 INFO: Setting up initial twist data...
2022-01-11 12:29:22,266 INFO: Twist setup complete.
2022-01-11 12:29:22,266 INFO: Searching for rational points on each twist...
2022-01-11 12:29:24,781 INFO: Finished searching for rational points on each twist.
2022-01-11 12:29:24,781 INFO: Testing local solvability of twists...
2022-01-11 12:29:24,786 INFO: Finished local solvability testing.
2022-01-11 12:29:24,787 INFO: Computing elliptic curve a-invariants...
2022-01-11 12:29:41,403 INFO: Finished computation of a-invariants.
2022-01-11 12:29:41,404 INFO: Computing MW group (delta = ['1', '-1'], g = [4, -16, 40, -20, 0, 1])...
2022-01-11 12:33:19,415 INFO: Finished MW computation (delta = ['1', '-1'], g = [4, -16, 40, -20, 0, 1])
2022-01-11 12:33:19,417 INFO: Computing MW group (delta = ['4', '-17', '42', '-21', '0', '1'], g = [4, -16, 40, -20, 0, 1])...
2022-01-11 12:38:59,103 INFO: Finished MW computation (delta = ['4', '-17', '42', '-21', '0', '1'], g = [4, -16, 40, -20, 0, 1])
2022-01-11 12:38:59,105 INFO: Computing MW group (delta = ['1'], g = [4, -16, 40, -20, 0, 1])...
2022-01-11 14:26:00,033 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16261.4MB, failed memory request: 1946.1MB
System Error: User memory limit has been reached
