2022-01-13 21:54:51,806 INFO: Initialized curve data.
2022-01-13 21:54:51,810 INFO: Setting up initial twist data...
2022-01-13 21:54:53,480 INFO: Twist setup complete.
2022-01-13 21:54:53,480 INFO: Searching for rational points on each twist...
2022-01-13 21:54:55,322 INFO: Finished searching for rational points on each twist.
2022-01-13 21:54:55,322 INFO: Testing local solvability of twists...
2022-01-13 21:54:59,271 INFO: Finished local solvability testing.
2022-01-13 21:54:59,272 INFO: Computing elliptic curve a-invariants...
2022-01-13 21:55:07,134 INFO: Finished computation of a-invariants.
2022-01-13 21:55:07,136 INFO: Computing MW group (delta = ['1', '-1', '1'], g = [-4, 5, 0, 0, 0, 4])...
2022-01-13 22:07:46,096 INFO: Finished MW computation (delta = ['1', '-1', '1'], g = [-4, 5, 0, 0, 0, 4])
2022-01-13 22:07:46,100 INFO: Skipped MW computation because no base point (delta = ['-4', '4', '1', '-1', '0', '4'])
2022-01-13 22:07:46,100 INFO: Computing MW group (delta = ['1'], g = [-4, 5, 0, 0, 0, 4])...
2022-01-13 22:20:11,591 INFO: Finished MW computation (delta = ['1'], g = [-4, 5, 0, 0, 0, 4])
2022-01-13 22:20:11,594 INFO: Computing MW group (delta = ['-4', '4', '0', '0', '0', '4'], g = [-4, 5, 0, 0, 0, 4])...
2022-01-14 00:51:16,426 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16364.8MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
