2022-02-01 12:33:57,481 INFO: Initialized curve data.
2022-02-01 12:33:57,485 INFO: Setting up initial twist data...
2022-02-01 12:33:58,983 INFO: Twist setup complete.
2022-02-01 12:33:58,984 INFO: Searching for rational points on each twist...
2022-02-01 12:34:01,329 INFO: Finished searching for rational points on each twist.
2022-02-01 12:34:01,330 INFO: Testing local solvability of twists...
2022-02-01 12:34:01,347 INFO: Finished local solvability testing.
2022-02-01 12:34:01,349 INFO: Computing elliptic curve a-invariants...
2022-02-01 12:34:11,512 INFO: Finished computation of a-invariants.
2022-02-01 12:34:11,514 INFO: Computing MW group (delta = ['4/3', '28/3', '163/3', '86/3', '16/3', '1/3'], g = [4, 29, 160, 86, 16, 1])...
2022-02-01 12:48:07,832 INFO: Finished MW computation (delta = ['4/3', '28/3', '163/3', '86/3', '16/3', '1/3'], g = [4, 29, 160, 86, 16, 1])
2022-02-01 12:48:07,835 INFO: Computing MW group (delta = ['1'], g = [4, 29, 160, 86, 16, 1])...
2022-02-01 12:52:59,178 INFO: Finished MW computation (delta = ['1'], g = [4, 29, 160, 86, 16, 1])
2022-02-01 12:52:59,181 INFO: Computing MW group (delta = ['1/3', '-1'], g = [4, 29, 160, 86, 16, 1])...
2022-02-01 15:14:26,392 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 514, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16363.0MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-02-02 04:48:24,311 INFO: Loaded curve data from file.
2022-02-02 04:48:24,312 INFO: Reducing MW generators...
2022-02-02 04:48:26,223 INFO: Finished reducing MW generators.
2022-02-02 04:48:26,226 INFO: Running elliptic Chabauty (delta = ['4/3', '28/3', '163/3', '86/3', '16/3', '1/3'], g = [4, 29, 160, 86, 16, 1])...
2022-02-02 04:48:56,019 INFO: Chabauty completed successfully (delta = ['4/3', '28/3', '163/3', '86/3', '16/3', '1/3'], g = [4, 29, 160, 86, 16, 1]).
2022-02-02 04:48:56,022 INFO: Skipped Chabauty because MW group hasn't been provably computed. (delta = ['1'], g = [4, 29, 160, 86, 16, 1])
2022-02-02 04:48:56,022 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1/3', '-1'], g = [4, 29, 160, 86, 16, 1])
2022-02-02 04:48:56,022 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['4', '28', '160', '86', '16', '1'], g = [4, 29, 160, 86, 16, 1])
2022-02-02 04:48:56,094 INFO: Tasks complete. Recording data and exiting.
