2022-01-12 12:31:12,996 INFO: Initialized curve data.
2022-01-12 12:31:12,998 INFO: Setting up initial twist data...
2022-01-12 12:31:14,223 INFO: Twist setup complete.
2022-01-12 12:31:14,223 INFO: Searching for rational points on each twist...
2022-01-12 12:31:16,804 INFO: Finished searching for rational points on each twist.
2022-01-12 12:31:16,805 INFO: Testing local solvability of twists...
2022-01-12 12:31:16,810 INFO: Finished local solvability testing.
2022-01-12 12:31:16,811 INFO: Computing elliptic curve a-invariants...
2022-01-12 12:31:26,027 INFO: Finished computation of a-invariants.
2022-01-12 12:31:26,029 INFO: Computing MW group (delta = ['4', '-12', '-15', '-2', '0', '-1'], g = [-4, 13, 16, 2, 0, 1])...
2022-01-12 12:48:50,306 INFO: Finished MW computation (delta = ['4', '-12', '-15', '-2', '0', '-1'], g = [-4, 13, 16, 2, 0, 1])
2022-01-12 12:48:50,309 INFO: Computing MW group (delta = ['1'], g = [-4, 13, 16, 2, 0, 1])...
2022-01-12 13:01:17,968 INFO: Finished MW computation (delta = ['1'], g = [-4, 13, 16, 2, 0, 1])
2022-01-12 13:01:17,971 INFO: Computing MW group (delta = ['-16', '52', '63', '7', '0', '4'], g = [-4, 13, 16, 2, 0, 1])...
2022-01-12 15:10:53,007 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16357.8MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-01-14 11:32:42,272 INFO: Loaded curve data from file.
2022-01-14 11:32:42,272 INFO: Reducing MW generators...
2022-01-14 11:32:43,120 INFO: Finished reducing MW generators.
2022-01-14 11:32:43,123 INFO: Running elliptic Chabauty (delta = ['4', '-12', '-15', '-2', '0', '-1'], g = [-4, 13, 16, 2, 0, 1])...
2022-01-14 11:32:57,687 INFO: Chabauty completed successfully (delta = ['4', '-12', '-15', '-2', '0', '-1'], g = [-4, 13, 16, 2, 0, 1]).
2022-01-14 11:32:57,689 INFO: Skipped Chabauty because MW group hasn't been provably computed. (delta = ['1'], g = [-4, 13, 16, 2, 0, 1])
2022-01-14 11:32:57,689 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-16', '52', '63', '7', '0', '4'], g = [-4, 13, 16, 2, 0, 1])
2022-01-14 11:32:57,689 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '12', '16', '2', '0', '1'], g = [-4, 13, 16, 2, 0, 1])
2022-01-14 11:32:57,732 INFO: Tasks complete. Recording data and exiting.
