2022-02-01 12:30:13,972 INFO: Initialized curve data.
2022-02-01 12:30:13,977 INFO: Setting up initial twist data...
2022-02-01 12:30:15,402 INFO: Twist setup complete.
2022-02-01 12:30:15,402 INFO: Searching for rational points on each twist...
2022-02-01 12:30:17,530 INFO: Finished searching for rational points on each twist.
2022-02-01 12:30:17,530 INFO: Testing local solvability of twists...
2022-02-01 12:30:31,994 INFO: Finished local solvability testing.
2022-02-01 12:30:31,996 INFO: Computing elliptic curve a-invariants...
2022-02-01 12:30:45,674 INFO: Finished computation of a-invariants.
2022-02-01 12:30:45,676 INFO: Computing MW group (delta = ['2', '-89/2', '177', '157/2', '11', '1/2'], g = [4, -88, 352, 157, 22, 1])...
2022-02-01 12:36:23,080 INFO: Finished MW computation (delta = ['2', '-89/2', '177', '157/2', '11', '1/2'], g = [4, -88, 352, 157, 22, 1])
2022-02-01 12:36:23,083 INFO: Computing MW group (delta = ['4', '-89', '352', '157', '22', '1'], g = [4, -88, 352, 157, 22, 1])...
2022-02-01 12:51:36,718 INFO: Finished MW computation (delta = ['4', '-89', '352', '157', '22', '1'], g = [4, -88, 352, 157, 22, 1])
2022-02-01 12:51:36,721 INFO: Computing MW group (delta = ['1'], g = [4, -88, 352, 157, 22, 1])...
2022-02-01 15:20:54,493 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 514, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16354.4MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
