2022-01-01 12:51:10,644 INFO: Initialized curve data.
2022-01-01 12:51:10,648 INFO: Setting up initial twist data...
2022-01-01 12:51:11,745 INFO: Twist setup complete.
2022-01-01 12:51:11,745 INFO: Searching for rational points on each twist...
2022-01-01 12:51:13,094 INFO: Finished searching for rational points on each twist.
2022-01-01 12:51:13,094 INFO: Testing local solvability of twists...
2022-01-01 12:51:45,335 INFO: Finished local solvability testing.
2022-01-01 12:51:45,336 INFO: Computing elliptic curve a-invariants...
2022-01-01 12:51:47,569 INFO: Finished computation of a-invariants.
2022-01-01 12:51:47,571 INFO: Skipped MW computation because no base point (delta = ['1/2', '9', '-1', '4', '-4'])
2022-01-01 12:51:47,572 INFO: Skipped MW computation because no base point (delta = ['2', '0', '13/2', '0', '3', '-2'])
2022-01-01 12:51:47,572 INFO: Skipped MW computation because no base point (delta = ['-1', '-1'])
2022-01-01 12:51:47,572 INFO: Skipped MW computation because no base point (delta = ['-2', '-4', '-13', '1', '-4', '6'])
2022-01-01 12:51:47,572 INFO: Computing MW group (delta = ['-4', '-8', '-8', '0', '0', '4'], g = [1, 2, 2])...
2022-01-01 12:51:49,898 INFO: Finished MW computation (delta = ['-4', '-8', '-8', '0', '0', '4'], g = [1, 2, 2])
2022-01-01 12:51:49,901 INFO: Computing MW group (delta = ['-4', '-8', '-8', '0', '0', '4'], g = [-4, 1, -2, 2])...
2022-01-01 13:17:19,334 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 327, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 7899.3MB, failed memory request: 1151.3MB
System Error: User memory limit has been reached
