2022-01-12 12:25:09,714 INFO: Initialized curve data.
2022-01-12 12:25:09,717 INFO: Setting up initial twist data...
2022-01-12 12:25:11,255 INFO: Twist setup complete.
2022-01-12 12:25:11,256 INFO: Searching for rational points on each twist...
2022-01-12 12:25:14,584 INFO: Finished searching for rational points on each twist.
2022-01-12 12:25:14,585 INFO: Testing local solvability of twists...
2022-01-12 12:25:20,363 INFO: Finished local solvability testing.
2022-01-12 12:25:20,364 INFO: Computing elliptic curve a-invariants...
2022-01-12 12:25:27,695 INFO: Finished computation of a-invariants.
2022-01-12 12:25:27,704 INFO: Skipped MW computation because no base point (delta = ['1/3', '-2/3', '1'])
2022-01-12 12:25:27,704 INFO: Computing MW group (delta = ['1/9', '-1/3', '8/9', '-1', '1'], g = [4, -11, 26, -19, 12, 16])...
2022-01-12 12:31:40,118 INFO: Finished MW computation (delta = ['1/9', '-1/3', '8/9', '-1', '1'], g = [4, -11, 26, -19, 12, 16])
2022-01-12 12:31:40,121 INFO: Computing MW group (delta = ['1'], g = [4, -11, 26, -19, 12, 16])...
2022-01-12 12:44:20,263 INFO: Finished MW computation (delta = ['1'], g = [4, -11, 26, -19, 12, 16])
2022-01-12 12:44:20,266 INFO: Computing MW group (delta = ['1/3', '-1/3', '1'], g = [4, -11, 26, -19, 12, 16])...
2022-01-12 15:04:08,883 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16201.7MB, failed memory request: 2530.1MB
System Error: User memory limit has been reached
2022-01-14 11:32:37,491 INFO: Loaded curve data from file.
2022-01-14 11:32:37,492 INFO: Reducing MW generators...
2022-01-14 11:32:38,689 INFO: Finished reducing MW generators.
2022-01-14 11:32:38,699 INFO: Skipped Chabauty because no base point (delta = ['1/3', '-2/3', '1'])
2022-01-14 11:32:38,700 INFO: Skipped Chabauty because MW group hasn't been provably computed. (delta = ['1/9', '-1/3', '8/9', '-1', '1'], g = [4, -11, 26, -19, 12, 16])
2022-01-14 11:32:38,700 INFO: Skipped Chabauty because MW group hasn't been provably computed. (delta = ['1'], g = [4, -11, 26, -19, 12, 16])
2022-01-14 11:32:38,700 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1/3', '-1/3', '1'], g = [4, -11, 26, -19, 12, 16])
2022-01-14 11:32:38,769 INFO: Tasks complete. Recording data and exiting.
